/*	SCCS Id: @(#)date.h	3.4	2002/02/03 */

/* This source file is generated by 'makedefs'.  Do not edit. */
#define BUILD_DATE "Sat Nov 21 19:47:42 2009"
#define BUILD_TIME (1258832862L)

#define VERSION_NUMBER 0x03040300UL
#define VERSION_FEATURES 0x003e0cc6UL
#define IGNORED_FEATURES 0x00800000UL
#define VERSION_SANITY1 0x211b117eUL
#define VERSION_SANITY2 0xa88195c8UL

#define VERSION_STRING "3.4.3"
#define VERSION_ID \
 "Unix NetHack Version 3.4.3 - last build Sat Nov 21 19:47:42 2009."

